apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: test-trigger
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: test-trigger
    spec:
      containers:
      - name: test-trigger
        image: cseboulderupskill.azurecr.io/example:v1
        env:
        - name: FUNCTIONS_WORKER_RUNTIME
          value: "python"
        - name: version
          value: "2.0"
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
---
apiVersion: v1
kind: Service
metadata:
  name: test-trigger
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: test-trigger
